// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_int int32

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgo_runtime_cgocallback runtime.cgocallback
func _cgo_runtime_cgocallback(unsafe.Pointer, unsafe.Pointer, uintptr, uintptr)

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, ...interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})

//go:cgo_import_static _cgo_c6d0445bb654_Cfunc_function_f
//go:linkname __cgofn__cgo_c6d0445bb654_Cfunc_function_f _cgo_c6d0445bb654_Cfunc_function_f
var __cgofn__cgo_c6d0445bb654_Cfunc_function_f byte
var _cgo_c6d0445bb654_Cfunc_function_f = unsafe.Pointer(&__cgofn__cgo_c6d0445bb654_Cfunc_function_f)

//go:cgo_unsafe_args
func _Cfunc_function_f(p0 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_c6d0445bb654_Cfunc_function_f, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
