var keywordlist = {
    "keywords":[
        "action",
        "requestId",
        "value",
        "ts",
        "path",
        "subscriptionId",
        "data",
        "dp",
        "filter",
        "authorization",
        "get",
        "set",
        "subscribe",
        "unsubscribe",
        "subscription",
        "nuint8",
        "uint8",
        "nuint16",
        "uint16",
        "nuint24",
        "uint24",
        "nuint32",
        "uint32",
        "bool",
        "float",
        "unknown"
    ]
};

