// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ClientId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientId) Reset()         { *m = ClientId{} }
func (m *ClientId) String() string { return proto.CompactTextString(m) }
func (*ClientId) ProtoMessage()    {}
func (*ClientId) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *ClientId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientId.Unmarshal(m, b)
}
func (m *ClientId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientId.Marshal(b, m, deterministic)
}
func (m *ClientId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientId.Merge(m, src)
}
func (m *ClientId) XXX_Size() int {
	return xxx_messageInfo_ClientId.Size(m)
}
func (m *ClientId) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientId.DiscardUnknown(m)
}

var xxx_messageInfo_ClientId proto.InternalMessageInfo

func (m *ClientId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SignalId struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            *NameSpace `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignalId) Reset()         { *m = SignalId{} }
func (m *SignalId) String() string { return proto.CompactTextString(m) }
func (*SignalId) ProtoMessage()    {}
func (*SignalId) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *SignalId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalId.Unmarshal(m, b)
}
func (m *SignalId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalId.Marshal(b, m, deterministic)
}
func (m *SignalId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalId.Merge(m, src)
}
func (m *SignalId) XXX_Size() int {
	return xxx_messageInfo_SignalId.Size(m)
}
func (m *SignalId) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalId.DiscardUnknown(m)
}

var xxx_messageInfo_SignalId proto.InternalMessageInfo

func (m *SignalId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignalId) GetNamespace() *NameSpace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type SignalInfo struct {
	Id                   *SignalId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MetaData             *MetaData `protobuf:"bytes,2,opt,name=metaData,proto3" json:"metaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignalInfo) Reset()         { *m = SignalInfo{} }
func (m *SignalInfo) String() string { return proto.CompactTextString(m) }
func (*SignalInfo) ProtoMessage()    {}
func (*SignalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *SignalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalInfo.Unmarshal(m, b)
}
func (m *SignalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalInfo.Marshal(b, m, deterministic)
}
func (m *SignalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalInfo.Merge(m, src)
}
func (m *SignalInfo) XXX_Size() int {
	return xxx_messageInfo_SignalInfo.Size(m)
}
func (m *SignalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SignalInfo proto.InternalMessageInfo

func (m *SignalInfo) GetId() *SignalId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SignalInfo) GetMetaData() *MetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

type MetaData struct {
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Max                  int32    `protobuf:"varint,5,opt,name=max,proto3" json:"max,omitempty"`
	Min                  int32    `protobuf:"varint,6,opt,name=min,proto3" json:"min,omitempty"`
	Unit                 string   `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	Size                 int32    `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	IsRaw                bool     `protobuf:"varint,9,opt,name=isRaw,proto3" json:"isRaw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaData) Reset()         { *m = MetaData{} }
func (m *MetaData) String() string { return proto.CompactTextString(m) }
func (*MetaData) ProtoMessage()    {}
func (*MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaData.Unmarshal(m, b)
}
func (m *MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaData.Marshal(b, m, deterministic)
}
func (m *MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaData.Merge(m, src)
}
func (m *MetaData) XXX_Size() int {
	return xxx_messageInfo_MetaData.Size(m)
}
func (m *MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetaData proto.InternalMessageInfo

func (m *MetaData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MetaData) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MetaData) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *MetaData) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *MetaData) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *MetaData) GetIsRaw() bool {
	if m != nil {
		return m.IsRaw
	}
	return false
}

type NameSpace struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameSpace) Reset()         { *m = NameSpace{} }
func (m *NameSpace) String() string { return proto.CompactTextString(m) }
func (*NameSpace) ProtoMessage()    {}
func (*NameSpace) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *NameSpace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameSpace.Unmarshal(m, b)
}
func (m *NameSpace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameSpace.Marshal(b, m, deterministic)
}
func (m *NameSpace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameSpace.Merge(m, src)
}
func (m *NameSpace) XXX_Size() int {
	return xxx_messageInfo_NameSpace.Size(m)
}
func (m *NameSpace) XXX_DiscardUnknown() {
	xxx_messageInfo_NameSpace.DiscardUnknown(m)
}

var xxx_messageInfo_NameSpace proto.InternalMessageInfo

func (m *NameSpace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Configuration struct {
	NetworkInfo          []*NetworkInfo `protobuf:"bytes,1,rep,name=networkInfo,proto3" json:"networkInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetNetworkInfo() []*NetworkInfo {
	if m != nil {
		return m.NetworkInfo
	}
	return nil
}

type NetworkInfo struct {
	Namespace            *NameSpace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type                 string     `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description          string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NetworkInfo) Reset()         { *m = NetworkInfo{} }
func (m *NetworkInfo) String() string { return proto.CompactTextString(m) }
func (*NetworkInfo) ProtoMessage()    {}
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *NetworkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfo.Unmarshal(m, b)
}
func (m *NetworkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfo.Marshal(b, m, deterministic)
}
func (m *NetworkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfo.Merge(m, src)
}
func (m *NetworkInfo) XXX_Size() int {
	return xxx_messageInfo_NetworkInfo.Size(m)
}
func (m *NetworkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfo proto.InternalMessageInfo

func (m *NetworkInfo) GetNamespace() *NameSpace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *NetworkInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NetworkInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type FrameInfo struct {
	SignalInfo           *SignalInfo   `protobuf:"bytes,1,opt,name=signalInfo,proto3" json:"signalInfo,omitempty"`
	ChildInfo            []*SignalInfo `protobuf:"bytes,2,rep,name=childInfo,proto3" json:"childInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FrameInfo) Reset()         { *m = FrameInfo{} }
func (m *FrameInfo) String() string { return proto.CompactTextString(m) }
func (*FrameInfo) ProtoMessage()    {}
func (*FrameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *FrameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameInfo.Unmarshal(m, b)
}
func (m *FrameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameInfo.Marshal(b, m, deterministic)
}
func (m *FrameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameInfo.Merge(m, src)
}
func (m *FrameInfo) XXX_Size() int {
	return xxx_messageInfo_FrameInfo.Size(m)
}
func (m *FrameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FrameInfo proto.InternalMessageInfo

func (m *FrameInfo) GetSignalInfo() *SignalInfo {
	if m != nil {
		return m.SignalInfo
	}
	return nil
}

func (m *FrameInfo) GetChildInfo() []*SignalInfo {
	if m != nil {
		return m.ChildInfo
	}
	return nil
}

type Frames struct {
	Frame                []*FrameInfo `protobuf:"bytes,1,rep,name=frame,proto3" json:"frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Frames) Reset()         { *m = Frames{} }
func (m *Frames) String() string { return proto.CompactTextString(m) }
func (*Frames) ProtoMessage()    {}
func (*Frames) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *Frames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frames.Unmarshal(m, b)
}
func (m *Frames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frames.Marshal(b, m, deterministic)
}
func (m *Frames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frames.Merge(m, src)
}
func (m *Frames) XXX_Size() int {
	return xxx_messageInfo_Frames.Size(m)
}
func (m *Frames) XXX_DiscardUnknown() {
	xxx_messageInfo_Frames.DiscardUnknown(m)
}

var xxx_messageInfo_Frames proto.InternalMessageInfo

func (m *Frames) GetFrame() []*FrameInfo {
	if m != nil {
		return m.Frame
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "base.Empty")
	proto.RegisterType((*ClientId)(nil), "base.ClientId")
	proto.RegisterType((*SignalId)(nil), "base.SignalId")
	proto.RegisterType((*SignalInfo)(nil), "base.SignalInfo")
	proto.RegisterType((*MetaData)(nil), "base.MetaData")
	proto.RegisterType((*NameSpace)(nil), "base.NameSpace")
	proto.RegisterType((*Configuration)(nil), "base.Configuration")
	proto.RegisterType((*NetworkInfo)(nil), "base.NetworkInfo")
	proto.RegisterType((*FrameInfo)(nil), "base.FrameInfo")
	proto.RegisterType((*Frames)(nil), "base.Frames")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x95, 0x93, 0xa6, 0x9b, 0x4c, 0x60, 0x59, 0x2c, 0x0e, 0x16, 0x07, 0x88, 0x2c, 0x21, 0x45,
	0x48, 0x04, 0xd4, 0xfd, 0x84, 0x5d, 0x90, 0xf6, 0xb0, 0x1c, 0xbc, 0x17, 0xae, 0x6e, 0xe2, 0x16,
	0x8b, 0xda, 0x8e, 0x12, 0x57, 0xa5, 0x7c, 0x04, 0xdf, 0x8c, 0xec, 0xb8, 0x49, 0x4a, 0x91, 0x38,
	0x65, 0xf2, 0xe6, 0xcd, 0xbc, 0x99, 0x37, 0x86, 0x67, 0xb5, 0x51, 0xca, 0xe8, 0xaa, 0xed, 0x8c,
	0x35, 0x78, 0xb1, 0xe6, 0xbd, 0xa0, 0x57, 0x90, 0x7c, 0x56, 0xad, 0x3d, 0xd2, 0xd7, 0x90, 0xde,
	0xed, 0xa4, 0xd0, 0xf6, 0xa1, 0xc1, 0xd7, 0x10, 0xc9, 0x86, 0xa0, 0x02, 0x95, 0x19, 0x8b, 0x64,
	0x43, 0x1f, 0x21, 0x7d, 0x92, 0x5b, 0xcd, 0x77, 0x0f, 0x0d, 0xc6, 0xb0, 0xd0, 0x5c, 0x89, 0x90,
	0xf5, 0x31, 0xfe, 0x00, 0x99, 0xfb, 0xf6, 0x2d, 0xaf, 0x05, 0x89, 0x0a, 0x54, 0xe6, 0xab, 0x17,
	0x95, 0x6b, 0x5f, 0x7d, 0xe5, 0x4a, 0x3c, 0x39, 0x98, 0x4d, 0x0c, 0xfa, 0x0d, 0x20, 0xb4, 0xd3,
	0x1b, 0x83, 0xdf, 0x8c, 0x62, 0xf9, 0xea, 0x7a, 0xa8, 0x3a, 0x89, 0x39, 0x71, 0xfc, 0x1e, 0x52,
	0x25, 0x2c, 0xbf, 0xe7, 0x96, 0x87, 0xde, 0x81, 0xf5, 0x18, 0x50, 0x36, 0xe6, 0xe9, 0x6f, 0x04,
	0xe9, 0x09, 0xc6, 0x05, 0xe4, 0x8d, 0xe8, 0xeb, 0x4e, 0xb6, 0x56, 0x1a, 0x4d, 0x16, 0x7e, 0xe0,
	0x39, 0x84, 0x6f, 0x20, 0x56, 0xfc, 0x27, 0x49, 0x0a, 0x54, 0x26, 0xcc, 0x85, 0x1e, 0x91, 0x9a,
	0x2c, 0x03, 0x22, 0xb5, 0xdb, 0x77, 0xaf, 0xa5, 0x25, 0x57, 0xc3, 0xbe, 0x2e, 0x76, 0x58, 0x2f,
	0x7f, 0x09, 0x92, 0x7a, 0x9a, 0x8f, 0xf1, 0x2b, 0x48, 0x64, 0xcf, 0xf8, 0x81, 0x64, 0x05, 0x2a,
	0x53, 0x36, 0xfc, 0xd0, 0xb7, 0x90, 0x8d, 0x16, 0xfc, 0xcb, 0x3a, 0x7a, 0x0f, 0xcf, 0xef, 0x8c,
	0xde, 0xc8, 0xed, 0xbe, 0xe3, 0x7e, 0xa6, 0x5b, 0xc8, 0xb5, 0xb0, 0x07, 0xd3, 0xfd, 0x70, 0xee,
	0x10, 0x54, 0xc4, 0x65, 0xbe, 0x7a, 0x19, 0xdc, 0x9c, 0x12, 0x6c, 0xce, 0xa2, 0x1d, 0xe4, 0xb3,
	0xdc, 0xf9, 0x3d, 0xd0, 0xff, 0xee, 0xe1, 0xe6, 0xb2, 0xc7, 0x76, 0xb8, 0x5c, 0xc6, 0x7c, 0xfc,
	0xb7, 0x79, 0xf1, 0x85, 0x79, 0x54, 0x41, 0xf6, 0xa5, 0xe3, 0x4a, 0x78, 0xc5, 0x4f, 0x00, 0xfd,
	0x78, 0xd2, 0x20, 0x79, 0x73, 0x76, 0x4c, 0x37, 0xf3, 0x8c, 0x83, 0x2b, 0xc8, 0xea, 0xef, 0x72,
	0xd7, 0xf8, 0x82, 0xc8, 0x6f, 0x79, 0x59, 0x30, 0x51, 0xe8, 0x47, 0x58, 0x7a, 0xb9, 0x1e, 0xbf,
	0x83, 0x64, 0xd3, 0x0d, 0x3e, 0xc6, 0xd3, 0x66, 0xe3, 0x2c, 0x6c, 0xc8, 0xae, 0x97, 0xfe, 0x99,
	0xdf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x22, 0x68, 0x8d, 0xc8, 0xf6, 0x02, 0x00, 0x00,
}
